openstack_user_name = "admin"
openstack_tenant_name = "admin"
openstack_auth_url = "https://192.168.0.2:5000/v3" # cambiar ip por la del servidor openstack
ubuntu_instance_name = "ubuntu"
#cirros_instance_name = "cirros"
security_groups = [ "default" ]
image_name = "cirros"
flavor_name = "m1.small"
network_name = "dev"
network_admin_state_up = "true"
openstack_router_name = "dev"
openstack_security_group_name = "allowssh-sg"
openstack_security_group_desc = "allowssh-sg"
from_port = 22
to_port = 22
ip_protocol = "tcp"
cidr = "0.0.0.0/0"
subnet_name = "dev-subnet"
subnet_cidr = "10.0.2.0/24"
prefix = "dev"
